#!/usr/bin/env bun
// Codegen CLI: turn one or more upstream `.d.ts` files into a
// workspace package full of zod schemas + matching inferred TS
// types.
//
// Usage:
//
//   bun scripts/codegen.ts \
//     --package <@scope/name> \
//     <input>[=<name>] [<input>[=<name>]]...
//
// One `<name>.zod.ts` is emitted per input under
// `packages/<basename-of-package>/src/`, where each file contains
// the zod schemas for every exported declaration in the source plus
// an `export type X = z.infer<typeof xSchema>` line for each. A
// barrel `src/index.ts` re-exports the per-input modules.
//
// Each input is preprocessed with the TypeScript compiler API
// before being handed to ts-to-zod: every `import` declaration is
// dropped, and any type reference that resolved through one of
// those imports (`sql.StatementResponse` from
// `import * as sql from "../sql"`, `ApiClient` from
// `import { ApiClient } from "../api-client"`, ...) is rewritten
// to `unknown`. ts-to-zod then emits `z.unknown()` for those
// fields, which is what we want - the codegen package is purely a
// data-shape surface, the runtime details from peer SDK modules
// don't belong here. Same outcome as a hand-tuned regex strip,
// except the AST walk handles every imported name on every input
// automatically without per-file tuning.
//
// On first run the CLI bootstraps the output package's hand-written
// boilerplate (`.gitignore`, `package.json`, `tsconfig.build.json`,
// `index.ts`) from the conventions other workspace packages already
// follow. On subsequent runs only the `src/` tree is regenerated;
// the boilerplate is left alone.
//
// `<basename>` for each input defaults to:
//   - the parent directory's name when the file is `model.d.ts`
//     (the SDK's `apis/<api>/model.d.ts` convention)
//   - the basename minus `.d.ts` / `.ts` otherwise
// Override with the `<path>=<name>` form.
//
// The output package is treated as a fully generated artifact: the
// `.gitignore` at the package root matches everything (`*`) so the
// boilerplate (`package.json`, `tsconfig.build.json`, `index.ts`)
// and the regenerated `src/` tree are both excluded from source
// control. The CLI is the source of truth - clean checkouts must
// run codegen before any workspace tooling that needs the package
// (e.g. `bun install` for workspace resolution).
//
// Safety: the CLI refuses to write or delete any file that exists
// and isn't already gitignored. The generator owns the gitignored
// tree - everything else (boilerplate, hand-written code, READMEs)
// is the developer's. If a stale checked-in artifact sits in the
// codegen target, the run aborts with a clear error and leaves the
// tree untouched.

import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { Command } from "commander";
import ts from "typescript";
import { generate } from "ts-to-zod";
import { bootstrapPackage } from "./codegen-bootstrap.js";
import { fail, ROOT, toRelative } from "./util.js";

interface CodegenInput {
  /** Absolute path to the source `.d.ts` file. */
  source: string;
  /** Output basename (e.g. `dashboards` -> emits `dashboards.zod.ts`). */
  name: string;
}

const HEADER = [
  "// AUTO-GENERATED by `bun scripts/codegen.ts` - DO NOT EDIT.",
  "// Regenerate via the matching root `prebuild` script.",
  "",
].join("\n");

function deriveName(path: string): string {
  const file = basename(path);
  // SDK convention: `apis/<api>/model.d.ts`. Use the parent
  // directory's name so `apis/dashboards/model.d.ts` -> `dashboards`.
  if (file === "model.d.ts" || file === "model.ts") return basename(dirname(path));
  return file.replace(/\.d\.ts$|\.ts$/, "");
}

function parseInputArg(value: string): CodegenInput {
  const eq = value.indexOf("=");
  if (eq === -1) return { source: value, name: deriveName(value) };
  return { source: value.slice(0, eq), name: value.slice(eq + 1) };
}

function resolvePackage(npmName: string): { dir: string; slug: string } {
  const slug = npmName.includes("/") ? (npmName.split("/").at(-1) ?? "") : npmName;
  if (!/^[a-z][a-z0-9-]*$/.test(slug)) {
    fail(`invalid package name: ${npmName} (slug ${JSON.stringify(slug)})`);
  }
  return { dir: resolve(ROOT, "packages", slug), slug };
}

/* ------------------------- ts-to-zod prep ------------------------- */

/**
 * Parse `entryPath` as TypeScript, drop every `import`
 * declaration, and rewrite any type reference whose root
 * identifier was introduced by one of those imports to the
 * `unknown` keyword. ts-to-zod sees a self-contained source where
 * the dropped peer modules surface as `z.unknown()` schemas.
 *
 * Two reference shapes get stubbed:
 *
 *   - `ns.X` (a `QualifiedName` in type position, or a
 *     `PropertyAccessExpression` in value position) where `ns` was
 *     introduced by `import * as ns from "..."`.
 *   - bare `X` where `X` was introduced by a default or named
 *     import (`import X from "..."`,
 *     `import { X } from "..."`, `import { Y as X } from "..."`).
 *
 * Comments and the rest of the file flow through unchanged.
 */
function stripImports(entryPath: string): string {
  const text = readFileSync(entryPath, "utf-8");
  const sf = ts.createSourceFile(
    entryPath,
    text,
    ts.ScriptTarget.Latest,
    /*setParentNodes*/ true,
    ts.ScriptKind.TS,
  );

  const namespaceAliases = new Set<string>();
  const importedNames = new Set<string>();
  for (const stmt of sf.statements) {
    if (!ts.isImportDeclaration(stmt) || !stmt.importClause) continue;
    const c = stmt.importClause;
    if (c.name) importedNames.add(c.name.text);
    const nb = c.namedBindings;
    if (!nb) continue;
    if (ts.isNamespaceImport(nb)) {
      namespaceAliases.add(nb.name.text);
    } else {
      for (const el of nb.elements) importedNames.add(el.name.text);
    }
  }

  const unknownType = (): ts.KeywordTypeNode =>
    ts.factory.createKeywordTypeNode(ts.SyntaxKind.UnknownKeyword);

  const transformer: ts.TransformerFactory<ts.SourceFile> =
    (context) => (root) => {
      const visitor: ts.Visitor = (node) => {
        if (ts.isImportDeclaration(node)) return undefined;

        // `ns.X` / `X` in TYPE position -> `unknown`. We only
        // stub when the root identifier came from an import; bare
        // references to local declarations stay untouched.
        if (ts.isTypeReferenceNode(node)) {
          const tn = node.typeName;
          if (
            ts.isQualifiedName(tn) &&
            ts.isIdentifier(tn.left) &&
            namespaceAliases.has(tn.left.text)
          ) {
            return unknownType();
          }
          if (ts.isIdentifier(tn) && importedNames.has(tn.text)) {
            return unknownType();
          }
        }

        // `ns.X` in VALUE position (rare in `.d.ts`, but possible
        // for `declare const x: typeof ns.foo` etc.). The
        // surrounding TypeQueryNode will get re-pointed at a
        // bare identifier; ts-to-zod will then either resolve it
        // locally or, if absent, fall back to `z.unknown()`.
        if (
          ts.isPropertyAccessExpression(node) &&
          ts.isIdentifier(node.expression) &&
          namespaceAliases.has(node.expression.text)
        ) {
          return node.name;
        }

        return ts.visitEachChild(node, visitor, context);
      };
      return ts.visitEachChild(root, visitor, context);
    };

  const result = ts.transform(sf, [transformer]);
  const printer = ts.createPrinter({ removeComments: false });
  const transformed = result.transformed[0] ?? sf;
  const out = printer.printFile(transformed);
  result.dispose();
  return out;
}

/**
 * Final shaping of the source before ts-to-zod sees it:
 *
 *   1. Promote every top-level `interface` / `type` to an `export`.
 *      ts-to-zod only emits schemas for exported declarations and
 *      bails on exported types that reference non-exported ones,
 *      so private SDK shells (`AuthorizationDetails`,
 *      `CronSchedule`, ...) need to flip to exports for the
 *      generator to see them.
 *   2. Rewrite each JSDoc block so its leading prose becomes a
 *      single `@description` tag. ts-to-zod parses the tag and
 *      emits a matching `.describe(...)` call on the schema field
 *      (introspectable via `schema.description`, picked up by
 *      `z.toJSONSchema`). The original prose is dropped so we
 *      don't see the same paragraph twice (once as the comment
 *      body, once as the `@description` tag that
 *      `keepComments: true` would otherwise carry through). Other
 *      tags (`@minimum`, `@format`, ...) flow through verbatim.
 */
function preprocess(source: string): string {
  let out = source.replace(/^(interface|type)\s/gm, "export $1 ");
  return out.replace(/\/\*\*([\s\S]*?)\*\//g, (match, body: string) => {
    if (/@description\b/.test(body)) return match;

    const lines = body
      .replace(/^\n/, "")
      .split("\n")
      .map((line) => line.replace(/^\s*\*\s?/, "").replace(/\s+$/, ""));

    const firstTagIdx = lines.findIndex((line) => /^@\w+/.test(line));
    const descLines = firstTagIdx === -1 ? lines : lines.slice(0, firstTagIdx);
    const tagLines = firstTagIdx === -1 ? [] : lines.slice(firstTagIdx);

    const description = descLines.join(" ").replace(/\s+/g, " ").trim();
    if (!description) return match;

    const rebuilt = [`@description ${description}`, ...tagLines];
    return `/**\n${rebuilt.map((line) => ` * ${line}`.trimEnd()).join("\n")}\n */`;
  });
}

/**
 * Take ts-to-zod's `getInferredTypes(...)` output - shaped for a
 * separate file (banner, `import { z } from "zod"`,
 * `import * as generated from "<schemas>"`, then
 * `export type X = z.infer<typeof generated.xSchema>` lines) - and
 * rewrite it for inclusion in the same file as the schemas:
 *
 *   - drop the banner and both imports (`z` is already imported,
 *     the schemas live right above)
 *   - drop the `generated.` namespace prefix from every reference
 *     so the type aliases bind to the colocated schema constants
 */
function inlineInferredTypes(inferredFile: string): string {
  return inferredFile
    .replace(/^\/\/ Generated by ts-to-zod\s*\n/, "")
    .replace(/^import \{ z \} from "zod";\s*\n+/m, "")
    .replace(/^import \* as generated from "[^"]*";\s*\n+/m, "")
    .replace(/\bgenerated\.(\w+)/g, "$1")
    .trim();
}

/* ------------------------ writability gate ----------------------- */

/**
 * Whether `git check-ignore` reports `absPath` as covered by an
 * ignore rule. One subprocess per call - cheap enough for the
 * handful of files codegen touches and avoids parsing `.gitignore`
 * patterns ourselves.
 *
 * Exit codes:
 *   - `0`: path is ignored.
 *   - `1`: path is not ignored.
 *   - anything else (e.g. `128` outside a worktree): treated as a
 *     hard error - we can't safely decide, so refuse.
 */
async function isGitIgnored(absPath: string): Promise<boolean> {
  const proc = Bun.spawn(["git", "check-ignore", "--quiet", absPath], {
    cwd: ROOT,
    stdout: "ignore",
    stderr: "ignore",
  });
  const code = await proc.exited;
  if (code === 0) return true;
  if (code === 1) return false;
  fail(
    `\`git check-ignore\` failed (exit ${code}) for ${toRelative(absPath)}; ` +
      `is the workspace inside a git worktree?`,
  );
}

/**
 * Refuse to clobber any file that exists and isn't already
 * gitignored. The CLI is supposed to own only the generated
 * (gitignored) tree; anything checked-in is a developer artifact
 * and must not be touched. Run before any write or delete.
 */
async function assertWritable(absPath: string): Promise<void> {
  if (!existsSync(absPath)) return;
  if (await isGitIgnored(absPath)) return;
  fail(
    `refusing to overwrite ${toRelative(absPath)}: file exists and is not gitignored. ` +
      `Move it out of the codegen target or add it to a parent .gitignore before regenerating.`,
  );
}

/* ---------------------------- driver ---------------------------- */

async function runGenerate(inputs: CodegenInput[], npmName: string): Promise<void> {
  if (inputs.length === 0) fail("at least one input file is required");

  const { dir: pkgDir, slug } = resolvePackage(npmName);
  const srcDir = resolve(pkgDir, "src");

  // Walk every existing file inside `srcDir` (the only tree we
  // wipe) and require it to be gitignored at the current state -
  // BEFORE bootstrap, so a freshly-dropped `.gitignore` doesn't
  // retroactively protect a hand-written file the developer just
  // added. Aborts with a clear error if any path is checked-in.
  if (existsSync(srcDir)) {
    const glob = new Bun.Glob("**/*");
    for await (const f of glob.scan({
      cwd: srcDir,
      absolute: true,
      onlyFiles: true,
      dot: true,
    })) {
      await assertWritable(f);
    }
  }

  // Lay down (or refresh) the package skeleton via the same helper
  // the `preinstall` hook uses. Idempotent - existing files are
  // left in place, missing ones are created.
  const rootMeta = (await Bun.file(resolve(ROOT, "package.json")).json()) as {
    version?: string;
  };
  await bootstrapPackage(npmName, slug, rootMeta.version ?? "0.0.0");

  // Wipe `src/` so deleted inputs can't leave stale modules behind.
  // The package's hand-written boilerplate (in `pkgDir` directly)
  // is left alone.
  rmSync(srcDir, { recursive: true, force: true });
  mkdirSync(srcDir, { recursive: true });

  const indexLines: string[] = [];
  let warnings = 0;

  for (const input of inputs) {
    const sourcePath = resolve(ROOT, input.source);
    if (!existsSync(sourcePath)) {
      fail(`codegen input not found: ${input.source}`);
    }

    console.log(`Generating ${input.name} from ${input.source}`);

    const sourceText = preprocess(stripImports(sourcePath));
    const { getZodSchemasFile, getInferredTypes, errors } = generate({
      sourceText,
      // Carry JSDoc through to the generated zod file so the
      // `@description` tag (and any other parsed tags) stays
      // visible at the call site alongside the matching
      // `.describe(...)`.
      keepComments: true,
    });
    if (errors.length) {
      warnings += errors.length;
      for (const err of errors) console.warn(`  ! ${err}`);
    }

    // ts-to-zod only adds an `import { ... } from <typesImportPath>`
    // line when the source references external types. Bundling
    // makes everything self-contained, so this path is never read
    // - pass a placeholder.
    const importPath = `./${input.name}.zod.js`;
    const schemas = getZodSchemasFile(importPath);
    const inferred = inlineInferredTypes(getInferredTypes(importPath));
    const content = HEADER + schemas.trimEnd() + "\n\n" + inferred + "\n";
    await Bun.write(resolve(srcDir, `${input.name}.zod.ts`), content);
    indexLines.push(`export * from "./${input.name}.zod.js";`);
  }

  await Bun.write(resolve(srcDir, "index.ts"), HEADER + indexLines.join("\n") + "\n");

  console.log(
    `Generated ${inputs.length} module(s) in ${pkgDir}/src/` +
      (warnings ? ` (${warnings} warning(s))` : ""),
  );
}

await new Command()
  .name("codegen")
  .description(
    "Generate zod schemas + inferred TypeScript types from one or more `.d.ts` files into a workspace package. The import + re-export graph rooted at each input is bundled via the TypeScript compiler API so peer modules (`import * as sql from \"../sql\"`) get inlined automatically.",
  )
  .argument(
    "<inputs...>",
    "Input `.d.ts` files. Use `<path>=<name>` to override the auto-derived basename.",
  )
  .requiredOption(
    "-p, --package <name>",
    "Output workspace package name (e.g. `@dbx-tools/sdk-shared`). Resolved to `packages/<basename>/`.",
  )
  .action(async (inputArgs: string[], opts: { package: string }) => {
    const inputs = inputArgs.map(parseInputArg);
    await runGenerate(inputs, opts.package);
  })
  .parseAsync(process.argv);
