#!/usr/bin/env bun
// Codegen driver: walk every workspace package, find ones whose
// `package.json` declares a `codegen` field, and turn the listed
// upstream `.d.ts` inputs into a colocated `generated/` tree of
// zod schemas + matching inferred TypeScript types.
//
// No CLI args. The single source of truth for "which packages get
// generated content, from which inputs" is each consumer package's
// own `package.json`:
//
//   {
//     "name": "@dbx-tools/sdk-shared",
//     "codegen": {
//       "inputs": [
//         "node_modules/@databricks/sdk-experimental/dist/apis/dashboards/model.d.ts"
//       ]
//     }
//   }
//
// Each entry under `inputs` is a path relative to the monorepo
// root, optionally suffixed with `=<name>` to override the
// auto-derived basename:
//
//   - `apis/dashboards/model.d.ts`        -> `dashboards.zod.ts`
//   - `apis/dashboards/model.d.ts=foo`    -> `foo.zod.ts`
//
// Per consumer package, codegen owns the `generated/` directory
// end-to-end:
//
//   - `generated/<name>.zod.ts`  one module per input, schemas
//     plus `export type X = z.infer<typeof xSchema>` lines.
//   - `generated/index.ts`        barrel re-export of every
//     module above.
//   - `generated/.gitignore`      `*\n` so the whole tree
//     (including this file) is excluded from source control.
//
// `package.json` is read-only to codegen - it sources `inputs` from
// the `codegen` field but never writes back. The generated tree is
// exposed through the hand-written top-level `index.ts` re-export
// (`export * from "./generated/index.js"`), which follows the same
// convention the rest of the workspace packages use and lets the
// publish merge in `scripts/release.ts` pick up the standard
// `package.default.json` exports map without any per-package
// wiring.
//
// Each input is preprocessed with the TypeScript compiler API
// before ts-to-zod sees it: every `import` declaration is dropped,
// and any type reference whose root identifier was introduced by
// one of those imports (`sql.StatementResponse` from
// `import * as sql from "../sql"`, `ApiClient` from
// `import { ApiClient } from "../api-client"`, ...) is rewritten
// to `unknown`. Codegen output is a pure data-shape surface; peer
// SDK runtime modules don't belong here.
//
// Safety: codegen refuses to write or delete any file inside
// `generated/` that isn't already gitignored at the start of the
// run. The gitignore lives inside `generated/.gitignore` and
// matches everything (`*`), so on a clean run every file passes.
// The check exists to catch developers who manually drop a file
// into `generated/` without updating the ignore - codegen aborts
// with a clear error rather than overwriting their work.

import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { basename, dirname, relative, resolve } from "node:path";
import ts from "typescript";
import { generate } from "ts-to-zod";
import {
  discoverPackages,
  fail,
  ROOT,
  toRelative,
  writeJson,
  type WorkspacePackage,
} from "./util.js";

interface CodegenInput {
  /** Absolute path to the source `.d.ts` file. */
  source: string;
  /** Output basename (e.g. `dashboards` -> emits `dashboards.zod.ts`). */
  name: string;
}

interface CodegenConfig {
  inputs: string[];
}

const HEADER = [
  "// AUTO-GENERATED by `bun scripts/codegen.ts` - DO NOT EDIT.",
  "// Regenerate via `bun run prebuild`.",
  "",
].join("\n");

const GENERATED_DIRNAME = "generated";

function deriveName(path: string): string {
  const file = basename(path);
  // SDK convention: `apis/<api>/model.d.ts`. Use the parent
  // directory's name so `apis/dashboards/model.d.ts` -> `dashboards`.
  if (file === "model.d.ts" || file === "model.ts") return basename(dirname(path));
  return file.replace(/\.d\.ts$|\.ts$/, "");
}

function parseInputArg(value: string): CodegenInput {
  const eq = value.indexOf("=");
  if (eq === -1) return { source: value, name: deriveName(value) };
  return { source: value.slice(0, eq), name: value.slice(eq + 1) };
}

/* ------------------------- ts-to-zod prep ------------------------- */

/**
 * Parse `entryPath` as TypeScript, drop every `import`
 * declaration, and rewrite any type reference whose root
 * identifier was introduced by one of those imports to the
 * `unknown` keyword. ts-to-zod sees a self-contained source where
 * the dropped peer modules surface as `z.unknown()` schemas.
 *
 * Two reference shapes get stubbed:
 *
 *   - `ns.X` (a `QualifiedName` in type position, or a
 *     `PropertyAccessExpression` in value position) where `ns` was
 *     introduced by `import * as ns from "..."`.
 *   - bare `X` where `X` was introduced by a default or named
 *     import (`import X from "..."`,
 *     `import { X } from "..."`, `import { Y as X } from "..."`).
 *
 * Comments and the rest of the file flow through unchanged.
 */
function stripImports(entryPath: string): string {
  const text = readFileSync(entryPath, "utf-8");
  const sf = ts.createSourceFile(
    entryPath,
    text,
    ts.ScriptTarget.Latest,
    /*setParentNodes*/ true,
    ts.ScriptKind.TS,
  );

  const namespaceAliases = new Set<string>();
  const importedNames = new Set<string>();
  for (const stmt of sf.statements) {
    if (!ts.isImportDeclaration(stmt) || !stmt.importClause) continue;
    const c = stmt.importClause;
    if (c.name) importedNames.add(c.name.text);
    const nb = c.namedBindings;
    if (!nb) continue;
    if (ts.isNamespaceImport(nb)) {
      namespaceAliases.add(nb.name.text);
    } else {
      for (const el of nb.elements) importedNames.add(el.name.text);
    }
  }

  const unknownType = (): ts.KeywordTypeNode =>
    ts.factory.createKeywordTypeNode(ts.SyntaxKind.UnknownKeyword);

  const transformer: ts.TransformerFactory<ts.SourceFile> =
    (context) => (root) => {
      const visitor: ts.Visitor = (node) => {
        if (ts.isImportDeclaration(node)) return undefined;

        // `ns.X` / `X` in TYPE position -> `unknown`. We only
        // stub when the root identifier came from an import; bare
        // references to local declarations stay untouched.
        if (ts.isTypeReferenceNode(node)) {
          const tn = node.typeName;
          if (
            ts.isQualifiedName(tn) &&
            ts.isIdentifier(tn.left) &&
            namespaceAliases.has(tn.left.text)
          ) {
            return unknownType();
          }
          if (ts.isIdentifier(tn) && importedNames.has(tn.text)) {
            return unknownType();
          }
        }

        // `ns.X` in VALUE position (rare in `.d.ts`, but possible
        // for `declare const x: typeof ns.foo` etc.). Drop the
        // namespace prefix so ts-to-zod sees a bare identifier.
        if (
          ts.isPropertyAccessExpression(node) &&
          ts.isIdentifier(node.expression) &&
          namespaceAliases.has(node.expression.text)
        ) {
          return node.name;
        }

        return ts.visitEachChild(node, visitor, context);
      };
      return ts.visitEachChild(root, visitor, context);
    };

  const result = ts.transform(sf, [transformer]);
  const printer = ts.createPrinter({ removeComments: false });
  const transformed = result.transformed[0] ?? sf;
  const out = printer.printFile(transformed);
  result.dispose();
  return out;
}

/**
 * Final shaping of the source before ts-to-zod sees it:
 *
 *   1. Promote every top-level `interface` / `type` to an `export`.
 *      ts-to-zod only emits schemas for exported declarations and
 *      bails on exported types that reference non-exported ones,
 *      so private SDK shells (`AuthorizationDetails`,
 *      `CronSchedule`, ...) need to flip to exports for the
 *      generator to see them.
 *   2. Rewrite each JSDoc block so its leading prose becomes a
 *      single `@description` tag. ts-to-zod parses the tag and
 *      emits a matching `.describe(...)` call on the schema field
 *      (introspectable via `schema.description`, picked up by
 *      `z.toJSONSchema`). The original prose is dropped so we
 *      don't see the same paragraph twice (once as the comment
 *      body, once as the `@description` tag that
 *      `keepComments: true` would otherwise carry through). Other
 *      tags (`@minimum`, `@format`, ...) flow through verbatim.
 */
function preprocess(source: string): string {
  let out = source.replace(/^(interface|type)\s/gm, "export $1 ");
  return out.replace(/\/\*\*([\s\S]*?)\*\//g, (match, body: string) => {
    if (/@description\b/.test(body)) return match;

    const lines = body
      .replace(/^\n/, "")
      .split("\n")
      .map((line) => line.replace(/^\s*\*\s?/, "").replace(/\s+$/, ""));

    const firstTagIdx = lines.findIndex((line) => /^@\w+/.test(line));
    const descLines = firstTagIdx === -1 ? lines : lines.slice(0, firstTagIdx);
    const tagLines = firstTagIdx === -1 ? [] : lines.slice(firstTagIdx);

    const description = descLines.join(" ").replace(/\s+/g, " ").trim();
    if (!description) return match;

    const rebuilt = [`@description ${description}`, ...tagLines];
    return `/**\n${rebuilt.map((line) => ` * ${line}`.trimEnd()).join("\n")}\n */`;
  });
}

/**
 * Take ts-to-zod's `getInferredTypes(...)` output - shaped for a
 * separate file (banner, `import { z } from "zod"`,
 * `import * as generated from "<schemas>"`, then
 * `export type X = z.infer<typeof generated.xSchema>` lines) - and
 * rewrite it for inclusion in the same file as the schemas:
 *
 *   - drop the banner and both imports (`z` is already imported,
 *     the schemas live right above)
 *   - drop the `generated.` namespace prefix from every reference
 *     so the type aliases bind to the colocated schema constants
 */
function inlineInferredTypes(inferredFile: string): string {
  return inferredFile
    .replace(/^\/\/ Generated by ts-to-zod\s*\n/, "")
    .replace(/^import \{ z \} from "zod";\s*\n+/m, "")
    .replace(/^import \* as generated from "[^"]*";\s*\n+/m, "")
    .replace(/\bgenerated\.(\w+)/g, "$1")
    .trim();
}

/* ------------------------ writability gate ----------------------- */

/**
 * Whether `git check-ignore` reports `absPath` as covered by an
 * ignore rule. One subprocess per call - cheap enough for the
 * handful of files codegen touches and avoids parsing `.gitignore`
 * patterns ourselves.
 *
 * Exit codes:
 *   - `0`: path is ignored.
 *   - `1`: path is not ignored.
 *   - anything else (e.g. `128` outside a worktree): treated as a
 *     hard error - we can't safely decide, so refuse.
 */
async function isGitIgnored(absPath: string): Promise<boolean> {
  const proc = Bun.spawn(["git", "check-ignore", "--quiet", absPath], {
    cwd: ROOT,
    stdout: "ignore",
    stderr: "ignore",
  });
  const code = await proc.exited;
  if (code === 0) return true;
  if (code === 1) return false;
  fail(
    `\`git check-ignore\` failed (exit ${code}) for ${toRelative(absPath)}; ` +
      `is the workspace inside a git worktree?`,
  );
}

/**
 * Refuse to clobber any file in `generated/` that exists and isn't
 * already gitignored. The gitignore is the codegen contract: every
 * file under `generated/` is owned by codegen, every file outside
 * is owned by the developer. Run before any write or delete inside
 * `generated/`.
 */
async function assertWritable(absPath: string): Promise<void> {
  if (!existsSync(absPath)) return;
  if (await isGitIgnored(absPath)) return;
  fail(
    `refusing to overwrite ${toRelative(absPath)}: file exists and is not gitignored. ` +
      `Move it out of \`generated/\` (codegen output) or update the ignore before regenerating.`,
  );
}

/* --------------------------- per-package --------------------------- */

/**
 * Regenerate the `generated/` tree for one consumer package and
 * stamp the package.json `module`/`main`/`exports` fields so the
 * tree is visible to import callers without manual wiring.
 */
async function generatePackage(pkg: WorkspacePackage): Promise<void> {
  const config = pkg.meta.codegen as CodegenConfig | undefined;
  if (!config?.inputs?.length) {
    fail(`${pkg.slug}: \`codegen.inputs\` is missing or empty`);
  }
  const inputs = config.inputs.map(parseInputArg);

  const generatedDir = resolve(pkg.dir, GENERATED_DIRNAME);

  // Walk every existing file inside `generated/` and require it
  // to be gitignored as of right now (BEFORE we touch the
  // gitignore itself), so a freshly-dropped `.gitignore` doesn't
  // retroactively protect a hand-written file the developer
  // staged. Aborts with a clear error if any path is checked-in.
  if (existsSync(generatedDir)) {
    const glob = new Bun.Glob("**/*");
    for await (const f of glob.scan({
      cwd: generatedDir,
      absolute: true,
      onlyFiles: true,
      dot: true,
    })) {
      await assertWritable(f);
    }
  }

  // Wipe and recreate `generated/` so deleted inputs can't leave
  // stale modules behind. The package's hand-written boilerplate
  // (in `pkg.dir` directly) is left alone.
  rmSync(generatedDir, { recursive: true, force: true });
  mkdirSync(generatedDir, { recursive: true });

  // The gitignore lives inside `generated/`, matching everything
  // (including itself, which is fine - git still consults the
  // file during ignore evaluation). On a fresh clone the dir
  // doesn't exist; codegen recreates it from scratch on demand.
  await Bun.write(resolve(generatedDir, ".gitignore"), "*\n");

  const indexLines: string[] = [];
  let warnings = 0;
  for (const input of inputs) {
    const sourcePath = resolve(ROOT, input.source);
    if (!existsSync(sourcePath)) {
      fail(`${pkg.slug}: codegen input not found: ${input.source}`);
    }

    console.log(`  ${input.name} <- ${input.source}`);

    const sourceText = preprocess(stripImports(sourcePath));
    const { getZodSchemasFile, getInferredTypes, errors } = generate({
      sourceText,
      // Carry JSDoc through to the generated zod file so the
      // `@description` tag (and any other parsed tags) stays
      // visible at the call site alongside the matching
      // `.describe(...)`.
      keepComments: true,
    });
    if (errors.length) {
      warnings += errors.length;
      for (const err of errors) console.warn(`    ! ${err}`);
    }

    // ts-to-zod only adds an `import { ... } from <typesImportPath>`
    // line when the source references external types. Bundling
    // makes everything self-contained, so this path is never read
    // - pass a placeholder.
    const importPath = `./${input.name}.zod.js`;
    const schemas = getZodSchemasFile(importPath);
    const inferred = inlineInferredTypes(getInferredTypes(importPath));
    const content = HEADER + schemas.trimEnd() + "\n\n" + inferred + "\n";
    await Bun.write(resolve(generatedDir, `${input.name}.zod.ts`), content);
    indexLines.push(`export * from "./${input.name}.zod.js";`);
  }

  await Bun.write(
    resolve(generatedDir, "index.ts"),
    HEADER + indexLines.join("\n") + "\n",
  );

  // Stamp the package.json so the generated tree is visible to
  // import callers without manual wiring. Surgical merge: leave
  // every other field (name, version, codegen, dependencies, ...)
  // alone.
  const entryRel = `${GENERATED_DIRNAME}/index.ts`;
  const entryExport = `./${entryRel}`;
  const updatedMeta = {
    ...pkg.meta,
    module: entryRel,
    main: entryRel,
    exports: { ".": entryExport },
  };
  await writeJson(pkg.jsonPath, updatedMeta);

  console.log(
    `${pkg.meta.name ?? pkg.slug}: ${inputs.length} module(s) -> ` +
      `${relative(ROOT, generatedDir)}/` +
      (warnings ? ` (${warnings} warning(s))` : ""),
  );
}

/* ------------------------------ driver ------------------------------ */

const targets = (await discoverPackages(() => true)).filter(
  (pkg) => (pkg.meta as { codegen?: unknown }).codegen,
);

if (targets.length === 0) {
  console.log("codegen: no workspace packages declare a `codegen` field");
} else {
  for (const pkg of targets) {
    await generatePackage(pkg);
  }
}
