#!/usr/bin/env bun
// Pre-`bun install` bootstrap for codegen-managed workspace
// packages.
//
// On a fresh clone the codegen output packages don't exist on disk
// (the entire directory is gitignored, see `scripts/codegen.ts`),
// so `bun install` can't resolve workspace deps that point at them.
// This script creates the minimal skeleton each named package
// needs to be visible to bun's workspace resolver:
//
//   - <pkg>/.gitignore           `*\n` (ignore everything)
//   - <pkg>/package.json         name + version + zod dep
//   - <pkg>/tsconfig.build.json  extends ../../tsconfig.build.json
//   - <pkg>/index.ts             re-exports `./src/index.js`
//   - <pkg>/src/index.ts         empty stub (replaced by codegen)
//
// The actual `src/<input>.zod.ts` schemas are emitted later by
// `bun scripts/codegen.ts` (which needs `node_modules`). This file
// is wired into the root `preinstall` lifecycle hook so
// `bun install` always succeeds, even on a fresh clone where the
// codegen output package isn't on disk yet.
//
// Usage:
//
//   bun scripts/codegen-bootstrap.ts <pkg-name> [<pkg-name>...]
//
// Package names default to the `@dbx-tools` scope when scope-less:
// `sdk-shared` is sugar for `@dbx-tools/sdk-shared`.
//
// Idempotent: every file is created only when missing, so existing
// codegen output (or developer-edited boilerplate) is left alone.
//
// Critical constraint: this script must run BEFORE `bun install`,
// so it must NOT import anything from `node_modules`. Stick to
// `node:*` and Bun built-ins.

import { existsSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const DEFAULT_SCOPE = "@dbx-tools";

function fail(message: string): never {
  console.error(`bootstrap: ${message}`);
  process.exit(1);
}

/**
 * Normalize `<scope>/<slug>` (or just `<slug>`) into both forms.
 * Adds the default scope when the input has no `@scope/` prefix
 * so callers can write `sdk-shared` instead of `@dbx-tools/sdk-shared`
 * everywhere.
 */
function parseNpmName(input: string): { npmName: string; slug: string } {
  const npmName = input.startsWith("@") ? input : `${DEFAULT_SCOPE}/${input}`;
  const parts = npmName.split("/");
  const slug = parts.length === 2 && parts[0]!.startsWith("@") ? parts[1]! : npmName;
  if (!/^[a-z][a-z0-9-]*$/.test(slug)) {
    fail(`invalid package name: ${input} (slug ${JSON.stringify(slug)})`);
  }
  return { npmName, slug };
}

async function writeIfMissing(path: string, content: string): Promise<boolean> {
  if (existsSync(path)) return false;
  await Bun.write(path, content);
  return true;
}

/**
 * Write the boilerplate skeleton for a codegen-managed package.
 * Each file is created only when missing so subsequent calls leave
 * existing content (codegen-emitted or developer-edited) intact.
 *
 * Returns the list of files this call actually wrote (for logging).
 * Reusable from `scripts/codegen.ts` so the full codegen and the
 * preinstall bootstrap stay in lock-step on the boilerplate shape.
 */
export async function bootstrapPackage(
  npmName: string,
  slug: string,
  version: string,
): Promise<{ dir: string; created: string[] }> {
  const dir = resolve(ROOT, "packages", slug);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const created: string[] = [];

  if (await writeIfMissing(resolve(dir, ".gitignore"), "*\n")) {
    created.push(".gitignore");
  }

  const pkgJson =
    JSON.stringify(
      {
        name: npmName,
        version,
        dependencies: { zod: "catalog:" },
        module: "index.ts",
        type: "module",
      },
      null,
      2,
    ) + "\n";
  if (await writeIfMissing(resolve(dir, "package.json"), pkgJson)) {
    created.push("package.json");
  }

  const tsconfig =
    JSON.stringify({ extends: "../../tsconfig.build.json" }, null, 2) + "\n";
  if (await writeIfMissing(resolve(dir, "tsconfig.build.json"), tsconfig)) {
    created.push("tsconfig.build.json");
  }

  const indexTs = [
    "/**",
    ` * \`${npmName}\`: zod schemas + inferred TypeScript types`,
    " * generated from upstream `.d.ts` declarations by",
    " * `scripts/codegen.ts`. The contents of `./src/` are",
    " * regenerated on every `bun run prebuild` and excluded from",
    " * source control.",
    " */",
    "",
    'export * from "./src/index.js";',
    "",
  ].join("\n");
  if (await writeIfMissing(resolve(dir, "index.ts"), indexTs)) {
    created.push("index.ts");
  }

  // Stub `src/index.ts` so consumers can `import` from the package
  // even before the full codegen has run (e.g. between
  // `preinstall` and `prebuild`). Replaced wholesale on the next
  // `bun run codegen`.
  const srcDir = resolve(dir, "src");
  if (!existsSync(srcDir)) mkdirSync(srcDir, { recursive: true });
  const srcIndexStub =
    "// PRE-CODEGEN STUB - regenerated by `bun run prebuild`.\nexport {};\n";
  if (await writeIfMissing(resolve(srcDir, "index.ts"), srcIndexStub)) {
    created.push("src/index.ts");
  }

  return { dir, created };
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    fail("usage: bun scripts/codegen-bootstrap.ts <pkg-name>...");
  }

  const rootMeta = (await Bun.file(resolve(ROOT, "package.json")).json()) as {
    version?: string;
  };
  const version = rootMeta.version ?? "0.0.0";

  for (const arg of args) {
    const { npmName, slug } = parseNpmName(arg);
    const { created } = await bootstrapPackage(npmName, slug, version);
    if (created.length === 0) {
      console.log(`bootstrap: ${npmName} already in place`);
    } else {
      console.log(`bootstrap: ${npmName} created ${created.join(", ")}`);
    }
  }
}
