#!/usr/bin/env bun
// Generate or refresh README.md for every publishable workspace
// package via the script agent (`scripts/util.ts`).
//
// Behavior:
//   - default: any package missing a README.md gets one generated by
//     the agent (which inspects the package source via `list_files`
//     / `read_files`, scoped to that package only). Packages with an
//     existing README are skipped.
//   - `--upgrade`: regenerate every README. The existing content is
//     passed to the agent as a starting point so accurate sections
//     can be preserved and drift gets rewritten.
//   - `--dry-run`: print the proposed README to stdout instead of
//     writing it back to disk.
//   - `--package <name>`: limit to a single package by full name
//     (e.g. `@dbx-tools/shared`).
//
// The agent is built with `cwd: pkg.dir` so `list_files` /
// `read_files` are sandboxed to that package directory and cannot
// reach into sibling packages while generating a README.

import { Command } from "commander";
import { resolve } from "node:path";
import { agentQuery, discoverPackages, fail, toRelative } from "./util.js";

const README_INSTRUCTIONS = `
You document a TypeScript package in the dbx-tools-appkit monorepo.
Your filesystem tools (list_files, read_files) are scoped to the
package directory. The package.json is at "package.json", entry
points are under "src/". \`read_files\` takes an array, so batch
related reads in one call.

Workflow:
1. read_files([{path: "package.json"}, {path: "src/index.ts"}]) to
   learn the package name, description, "main"/"exports", and the
   exports the README should cover.
2. Use list_files + a follow-up read_files batch on the rest of
   src/* only as needed to describe the surface area accurately.

Output: a complete README.md as plain markdown with these sections,
in order:

- # <package name>
- One short paragraph: what the package does and who it's for.
- ## Installation - one bun add snippet.
- ## Usage - one minimal runnable code example.
- ## API - bullets listing the main public exports, one short line each.

Style:
- No preamble, no closing remarks.
- No emojis.
- No em dashes.
- Output only the README markdown body. Do NOT wrap the whole output
  in a triple-backtick fence; only fence actual code snippets.
`.trim();

const program = new Command()
  .name("readme")
  .description("Generate or refresh README.md across publishable workspace packages.")
  .option("-u, --upgrade", "regenerate READMEs that already exist", false)
  .option("-n, --dry-run", "print to stdout instead of writing", false)
  .option(
    "-p, --package <name>",
    "limit to a single package by full name (e.g. @dbx-tools/shared)",
  )
  .parse(process.argv);

const {
  upgrade,
  dryRun,
  package: only,
} = program.opts<{
  upgrade: boolean;
  dryRun: boolean;
  package?: string;
}>();

const all = await discoverPackages();
const pkgs = only ? all.filter((p) => p.meta.name === only) : all;
if (pkgs.length === 0) fail(`No packages matched ${only ?? "(all publishable)"}`);

let wrote = 0;
let skipped = 0;
let failed = 0;

for (const pkg of pkgs) {
  const readmePath = resolve(pkg.dir, "README.md");
  const existing = await Bun.file(readmePath)
    .text()
    .catch(() => null);

  if (existing && !upgrade) {
    skipped++;
    console.log(`skip ${pkg.meta.name} (README exists; pass --upgrade to refresh)`);
    continue;
  }

  const mode = existing ? "upgrade" : "new";
  const prompt = existing
    ? `Refresh the README for ${pkg.meta.name}. Use the existing README below as a starting point: keep sections that are still accurate, rewrite anything that's drifted from the current code.\n\n--- existing README ---\n${existing}`
    : `Write a README for ${pkg.meta.name} from scratch by inspecting its source.`;

  console.log(`> ${pkg.meta.name} (${mode})`);
  const md = await agentQuery(prompt, undefined, {
    instructions: README_INSTRUCTIONS,
    cwd: pkg.dir,
  });
  if (!md) {
    failed++;
    console.warn(`  no agent output (skipping; check Databricks auth)`);
    continue;
  }

  const body = md.endsWith("\n") ? md : `${md}\n`;
  if (dryRun) {
    console.log(`\n--- ${pkg.meta.name}: ${toRelative(readmePath)} ---\n${body}`);
  } else {
    await Bun.write(readmePath, body);
    wrote++;
    console.log(`  wrote ${toRelative(readmePath)}`);
  }
}

console.log(
  `\nDone: ${wrote} written, ${skipped} skipped, ${failed} failed (of ${pkgs.length} package(s))${
    dryRun ? " [--dry-run, nothing persisted]" : ""
  }.`,
);
